sudo: false
language: node_js
node_js:
  - 8
install:
  - bundle install --deployment --jobs=3 --retry=3
cache:
  directories:
    - node_modules
    - vendor/bundle
before_script:
  - npm prune
script:
  - npm run lint
