#
# Jekyll configuration
#

# site settings
name: Sonnie
description: The personal site of Sonnie Nguyen. A blog where you can find content on everything related to web development.
baseurl: "" # the subpath of your site, e.g. /blog
url: https://www.sonnienguyen.com
excerpt_separator: <!-- more -->

# site author
author:
  name: Sonnie Nguyen
  bio: Coding Journal
  email: info@sonnienguyen.com
  avatar: https://avatars2.githubusercontent.com/u/16827429?s=88&v=4

# collections
collections:
  categories:
    output: true

# navigation settings
navigation:
- text: About
  url: /about/
- text: Posts
  url: /
  layout: post
- text: Archives
  url: /posts/archives/

# social
footer-links:
  facebook:
  github: sonnienguyen
  instagram: sonniephotography
  codepen: sonnienguyen
  linkedin:
  rss: # just type anything here for a working RSS icon
  twitter:
  youtube: # channel/<your_long_string> or user/<user-name>

# outputting
source: site
permalink: /:title/
paginate: 10 # amount of posts to show
paginate_path: /page:num/

# defaults
defaults:
  - scope:
      path: _categories
    values:
      layout: category

# markdown
kramdown:
  input: GFM
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    css_class: 'highlight'

plugins:
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-paginate
  - jemoji

include:
  # include files inside _pages directory
  - _pages
