#
# Site configuration.
#

# site settings
name: Sonnie
description: The personal site of Sonnie Nguyen. A blog where you can find content on everything related to web development.
url: https://www.sonnienguyen.com
excerpt_separator: <!-- more -->

# site author
author:
  name: Sonnie Nguyen
  bio: Coding Journal
  email: info@sonnienguyen.com
  avatar: https://avatars2.githubusercontent.com/u/16827429?s=88&v=4

# collections
collections:
  categories:
    output: true

# navigation settings
navigation:
- text: About
  url: /about/
- text: Posts
  url: /
  layout: post
- text: Archives
  url: /posts/archives/

# social
footer-links:
  github: sonnienguyen
  instagram: sonniephotography
  codepen: sonnienguyen

# outputting
permalink: /:title/
paginate: 10 # amount of posts to show
paginate_path: /page:num/

# defaults
defaults:
  - scope:
      path: _categories
    values:
      layout: category

# markdown
kramdown:
  input: GFM
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    css_class: 'highlight'

# server settings
source: ./docs
baseurl: ""
host: 0.0.0.0
port: 9001
encoding: UTF-8

plugins:
  - jekyll-sitemap
  - jekyll-paginate
  - jemoji

include:
  # include files inside _pages directory
  - _pages
